### ISSUE TITLE
Error running with default options, MacOS 10.12

### ISSUE THREAD

**Issue by mschumak** [KitwareMedical/SlicerCustomAppTemplate#5]
I just tried running cookiecutter with the default options. My system is MacOS 10.12. The command line and output are as follows:

```
$ cookiecutter gh:KitwareMedical/SlicerCustomAppTemplate

You've downloaded /Users/michaelschumaker/.cookiecutters/SlicerCustomAppTemplate before. Is it okay to delete and re-download it? [yes]: 
project_name [SlicerCustomAppTemplate]: 
github_organization [Kitware]: 
github_project [SlicerCustomAppTemplate]: 
org_domain [kitware.com]: 
org_name [Kitware, Inc.]: 
app_name [SlicerCustomAppTemplate]: 
app_version_major [0]: 
app_version_minor [1]: 
app_version_patch [0]: 
app_description_summary [Customized version of Slicer]: 
Traceback (most recent call last):
  File "/usr/local/bin/cookiecutter", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/cookiecutter/cli.py", line 120, in main
    password=os.environ.get('COOKIECUTTER_REPO_PASSWORD')
  File "/Library/Python/2.7/site-packages/cookiecutter/main.py", line 94, in cookiecutter
    output_dir=output_dir
  File "/Library/Python/2.7/site-packages/cookiecutter/generate.py", line 364, in generate_files
    generate_file(project_dir, infile, context, env)
  File "/Library/Python/2.7/site-packages/cookiecutter/generate.py", line 172, in generate_file
    rendered_file = tmpl.render(**context)
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "./CMakeLists.txt", line 22, in top-level template code
  File "/Library/Python/2.7/site-packages/jinja2_github.py", line 26, in _head
    return Github().get_repo(repo).get_branch(repo_branch).commit.sha
  File "/Library/Python/2.7/site-packages/github/Repository.py", line 1242, in get_branch
    self.url + "/branches/" + branch
  File "/Library/Python/2.7/site-packages/github/Requester.py", line 260, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "/Library/Python/2.7/site-packages/github/Requester.py", line 317, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/Library/Python/2.7/site-packages/github/Requester.py", line 370, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "/Library/Python/2.7/site-packages/github/Requester.py", line 394, in __requestRaw
    response = cnx.getresponse()
  File "/Library/Python/2.7/site-packages/github/Requester.py", line 107, in getresponse
    r = verb(url, headers=self.headers, data=self.input, timeout=self.timeout, verify=self.verify)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 511, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/Slicer/Slicer/branches/master (Caused by SSLError(SSLError(1, u'[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)'),))
```

**Comment by jcfr** [comment]
I suggest you use python 3.x, here is what I do on macOS:

```
cd /tmp/
python3.6 -m venv ./cookiecutter
. ./cookiecutter/bin/activate
python -m pip install --upgrade pip 
pip install cookiecutter jinja2-github
cookiecutter gh:KitwareMedical/SlicerCustomAppTemplate
```

For completness, I also tried with Python 2.7, and here is what I get the same error as you:

```
cd /tmp/
python -m virtualenv ./cookiecutter-py27
. ./cookiecutter-py27/bin/activate
python -m pip install --upgrade pip 
pip install cookiecutter jinja2-github
cookiecutter gh:KitwareMedical/SlicerCustomAppTemplate
[...]
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/Slicer/Slicer/branches/master (Caused by SSLError(SSLError(1, u'[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)'),))
```

**Comment by mschumak** [comment]
Excellent, thank you. Running it with Python 3 worked.
